# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c50cabfdff68f7a59d182122ffe82d1c72d68956d246630d39e75ce351d70c97f763c4ba18a4b7b965158508484ea89d2598fbaa19365d3b52b0329ec3fe724

test:
  secret_key_base: 8fb48fa9c54bc0b4719f032b21d36041abcd8dd6fea538fc47f5c1ee80a3852ab63a06ed97608a3ff8f8b3f8e34aee0f436c0b5c6f072fbb520a3bfbc01bbe4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
